# Generated by Django 5.1.5 on 2025-11-22 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0048_program_recruit_type'),
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='progress.programlesson'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='programlesson',
            name='order',
            field=models.PositiveIntegerField(help_text='차시 번호'),
        ),
        migrations.AlterUniqueTogether(
            name='programlesson',
            unique_together={('program', 'order')},
        ),
    ]
