# Generated by Django 5.1.5 on 2025-11-01 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='출강장소명')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='주소')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='담당강사')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(choices=[('1부', '1부'), ('2부', '2부'), ('3부', '3부')], max_length=10, verbose_name='부서')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='정원')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='students.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=10, verbose_name='학년')),
                ('class_name', models.CharField(max_length=10, verbose_name='반')),
                ('number', models.CharField(max_length=10, verbose_name='번호')),
                ('name', models.CharField(max_length=50, verbose_name='학생 이름')),
                ('parent_contact', models.CharField(max_length=20, verbose_name='학부모 연락처')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.programdivision')),
            ],
        ),
    ]
