# Generated by Django 5.1.5 on 2025-11-01 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0007_career_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programdivision',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='teachers.teachinginstitution'),
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
