# Generated by Django 5.1.5 on 2026-07-08 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_programdivision_institution_delete_institution'),
        ('teachers', '0010_teachinginstitution_closed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='medutech_student_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='medutech 학생 ID'),
        ),
        migrations.CreateModel(
            name='MedutechAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_token', models.CharField(max_length=64, verbose_name='API 토큰')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medutech_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedutechSchoolMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medutech_school_id', models.IntegerField(verbose_name='medutech 학교 ID')),
                ('medutech_school_name', models.CharField(blank=True, max_length=100, verbose_name='medutech 학교명')),
                ('medutech_program_name', models.CharField(blank=True, max_length=100, verbose_name='medutech 프로그램명')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medutech_mapping', to='teachers.teachinginstitution')),
            ],
        ),
    ]
