# Generated by Django 5.1.5 on 2026-08-28 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_medutech_student_id_medutechaccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_priority',
            field=models.BooleanField(default=False, verbose_name='자리 우선배정 대상'),
        ),
    ]
