"""
Django settings for making_site project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 환경변수 로드
env = environ.Env()
env.read_env(os.path.join(BASE_DIR, ".env"))

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'   # ✅ URL prefix는 항상 / 로 시작해야 함
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # ✅ collectstatic 결과물 저장소

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # 앱 외부 공용 static (선택사항)
]
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r99=5t4i!z6t_)joe(kvukz*uc)rnxpz0ntpp+2$=apv1$!&s6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '168.107.32.34', 
    '133.186.144.151', 
    'localhost', 
    '127.0.0.1', 
    '172.30.1.100',
    'steam-making.com',
    'www.steam-making.com'
]

HOLIDAY_API_KEY = "여기에_발급받은_API_KEY_입력"

KAKAO_REST_API_KEY = "00b9459c0c60c9c475e7ccbc88abc6e0"

ESTIMATE_VENDOR = {
    "business_no": "420-03-01408",
    "name": "메듀테크",
    "address": "광주광역시 서구 화개중앙로 51 5층",
    "biz_type": "도소매, 서비스",
    "tel": "062-365-1553",
    "mobile": "010-9890-1553",
    "fax" : "0504-432-1553",
    "bank": "국민 772601-01-707471",
    "logo_path": os.path.join(BASE_DIR, "static", "images", "making_stamp.png"),
}

# Application definition

INSTALLED_APPS = [
    "grappelli", 
    "filebrowser", 
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'main',
    'accounts', # 회원관리 앱 추가
    'materials',  # ✅ 교구재 관리 앱 추가
    'photobook',
    'attendance',  # ✅ 출결 앱 등록
    'rest_framework', 
    'widget_tweaks',
    'teachers',
    "notices",
    "courses",
    "lotto_predictor",
    'redirects',
    'class_resources',
    'tasks',
    'robot_LvUP',
    'students',
    "blog_auto",
    'pycode',
    'progress',
    'recruit',
    'schools',
    'linkhub',
    "typing_trainer",
    'django_crontab',
    'openbanking',
]

CRONJOBS = [
    # 매일 오전 8시 linkhub 수집 + 만료 자동삭제
    ('0 8 * * *', 'django.core.management.call_command', ['collect_linkhub']),
]

# 🔐 API 키는 .env로 빼는 걸 추천
OPENAI_API_KEY = env("OPENAI_API_KEY")

# 오픈뱅킹
OPENBANKING_CLIENT_ID = env("OPENBANKING_CLIENT_ID", default="")
OPENBANKING_CLIENT_SECRET = env("OPENBANKING_CLIENT_SECRET", default="")
OPENBANKING_REDIRECT_URI = env("OPENBANKING_REDIRECT_URI", default="")
OPENBANKING_SMS_TOKEN = env("OPENBANKING_SMS_TOKEN", default="")

# 네이버 블로그
NAVER_BLOG_ACCESS_TOKEN = env("NAVER_BLOG_ACCESS_TOKEN")
NAVER_BLOG_NAME = env("NAVER_BLOG_NAME")  # 네이버 블로그 ID

NAVER_COOKIE_NID_AUT = env("NAVER_COOKIE_NID_AUT")
NAVER_COOKIE_NID_SES = env("NAVER_COOKIE_NID_SES")

# 티스토리
#TISTORY_ACCESS_TOKEN = env("TISTORY_ACCESS_TOKEN")
#TISTORY_BLOG_NAME = env("TISTORY_BLOG_NAME")  # 티스토리 블로그 URL 이름

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'making_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main.context_processors.menu_items', # ✅ 동적 메뉴용 컨텍스트 프로세서 추가
            ],
        },
    },
]

WSGI_APPLICATION = 'making_site.wsgi.application'

SITE_ID = 1


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 로그인 성공 후 리디렉트할 페이지 설정
LOGIN_REDIRECT_URL = 'redirect_after_login'
LOGOUT_REDIRECT_URL = '/accounts/login/'  # 로그아웃 후 로그인 페이지로 이동

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Filebrowser settings
FILEBROWSER_DIRECTORY = ""  # media/ 바로 밑에서 시작
FILEBROWSER_DEFAULT_PERMISSIONS = True
FILEBROWSER_OVERWRITE_EXISTING = False
FILEBROWSER_DELETE_ALLOWED = True
VERSIONS_BASEDIR = "media/_versions"  # ✅ 버전 저장소 경로 지정

# settings.py
AUTHENTICATION_FORM = 'accounts.forms.CustomAuthenticationForm'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.naver.com'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False  # SSL과 TLS 중복 설정 금지
EMAIL_HOST_USER = 'robotmaking@naver.com'  # 네이버 이메일 주소
EMAIL_HOST_PASSWORD = 'CEUN94GM5QFL'       # 네이버 메일 로그인 비밀번호
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

ADMINS = [('Admin', 'robotmaking@naver.com')]

from django.contrib.messages import constants as messages

MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'
