# Generated by Django 5.1.5 on 2025-07-31 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0003_teachingday_remove_teachinginstitution_day_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='교구재 이름')),
                ('consumer_price', models.PositiveIntegerField(default=0, verbose_name='소비자가')),
                ('school_price', models.PositiveIntegerField(default=0, verbose_name='학교납품가')),
                ('institute_price', models.PositiveIntegerField(default=0, verbose_name='기관납품가')),
                ('supply_price', models.PositiveIntegerField(default=0, verbose_name='공급가')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='재고')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='거래처명')),
                ('contact', models.CharField(blank=True, max_length=50, verbose_name='연락처')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='주소')),
            ],
        ),
        migrations.CreateModel(
            name='VendorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_month', models.CharField(max_length=7, verbose_name='주문 년월')),
                ('expected_date', models.DateField(verbose_name='예상 입고일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teachinginstitution', verbose_name='출강 장소')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='강사ID')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_month', models.CharField(max_length=7, verbose_name='주문 년월')),
                ('release_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teachinginstitution', verbose_name='출강 장소')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='강사ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='주문년도')),
                ('order_month', models.PositiveIntegerField(blank=True, null=True, verbose_name='주문월')),
                ('quantity', models.PositiveIntegerField()),
                ('ordered_date', models.DateField(auto_now_add=True)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ordered', '주문완료'), ('waiting', '입고대기'), ('received', '입고완료')], default='ordered', max_length=10)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teachinginstitution', verbose_name='출강장소')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='강사')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date', models.DateField(auto_now_add=True)),
                ('received_quantity', models.PositiveIntegerField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='materials.order')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialReleaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', '출고대기'), ('released', '출고완료')], default='pending', max_length=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='materials.materialrelease')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='수량')),
                ('status', models.CharField(choices=[('waiting', '입고대기'), ('received', '입고완료')], default='waiting', max_length=10)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material', verbose_name='교구재')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='materials.materialorder')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.vendor', verbose_name='거래처')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.vendor', verbose_name='거래처명'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.vendortype', verbose_name='종류'),
        ),
        migrations.AddField(
            model_name='material',
            name='vendor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.vendortype', verbose_name='거래처 종류'),
        ),
    ]
