# Generated by Django 5.1.5 on 2025-07-31 16:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrelease',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
