# Generated by Django 5.1.5 on 2025-07-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_materialrelease_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrelease',
            name='order_month',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='주문 년월'),
        ),
    ]
