# Generated by Django 5.1.5 on 2025-07-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_materialrelease_order_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrelease',
            name='order_month',
            field=models.CharField(blank=True, default='2025-08', max_length=7, null=True, verbose_name='주문 년월'),
        ),
    ]
