# Generated by Django 5.1.5 on 2025-07-31 17:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_alter_materialrelease_order_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='주문일자'),
        ),
    ]
