# Generated by Django 5.1.5 on 2025-07-31 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_alter_order_ordered_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='order',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_date',
            field=models.DateField(blank=True, null=True, verbose_name='예상 입고일'),
        ),
        migrations.AlterField(
            model_name='order',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material', verbose_name='교구재'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='수량'),
        ),
    ]
