# Generated by Django 5.1.5 on 2025-07-31 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_remove_order_institution_remove_order_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialorder',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='materialorder',
            name='teacher',
        ),
    ]
