# Generated by Django 5.1.5 on 2025-08-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_materialorder_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrelease',
            name='expected_date',
            field=models.DateField(blank=True, null=True, verbose_name='출고 예정일'),
        ),
    ]
