# Generated by Django 5.1.5 on 2025-08-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_materialrelease_expected_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialreleaseitem',
            name='unit_price',
            field=models.PositiveIntegerField(default=0, verbose_name='납품가'),
        ),
    ]
