# Generated by Django 5.1.5 on 2025-08-11 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0010_materialreleaseitem_unit_price'),
        ('teachers', '0003_teachingday_remove_teachinginstitution_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleasePaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_month', models.CharField(max_length=7)),
                ('status', models.CharField(choices=[('unpaid', '미수금'), ('paid', '수금완료')], default='unpaid', max_length=10)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_payments', to='teachers.teachinginstitution')),
            ],
            options={
                'unique_together': {('institution', 'order_month')},
            },
        ),
    ]
