# Generated by Django 5.1.5 on 2025-08-11 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0011_releasepaymentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrelease',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', '미수금'), ('partial', '부분수금'), ('paid', '수금완료')], default='unpaid', max_length=20, verbose_name='수금 상태'),
        ),
    ]
