# Generated by Django 5.1.5 on 2025-08-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0012_materialrelease_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrelease',
            name='release_method',
            field=models.CharField(choices=[('택배', '택배'), ('센터수령', '센터수령')], default='택배', max_length=20, verbose_name='출고방법'),
        ),
    ]
