# Generated by Django 5.1.5 on 2025-08-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0013_materialrelease_release_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialreleaseitem',
            name='release_method',
            field=models.CharField(choices=[('택배', '택배'), ('센터수령', '센터수령')], default='택배', max_length=20, verbose_name='출고방법'),
        ),
    ]
