# Generated by Django 5.1.5 on 2025-08-13 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0014_materialreleaseitem_release_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialreleaseitem',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
