# Generated by Django 5.1.5 on 2025-08-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0015_materialreleaseitem_released_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrelease',
            name='estimate_sent',
            field=models.BooleanField(default=False, verbose_name='견적서 발행 여부'),
        ),
    ]
