# Generated by Django 5.1.5 on 2025-08-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0016_materialrelease_estimate_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialreleaseitem',
            name='order_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialreleaseitem',
            name='order_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
