# Generated by Django 5.1.5 on 2025-08-30 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0017_materialreleaseitem_order_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialreleaseitem',
            name='order_month',
        ),
        migrations.RemoveField(
            model_name='materialreleaseitem',
            name='order_year',
        ),
    ]
