# Generated by Django 5.1.5 on 2025-08-31 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0018_remove_materialreleaseitem_order_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialorderitem',
            name='paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='입금일자'),
        ),
    ]
