# Generated by Django 5.1.5 on 2025-08-31 07:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0019_materialorderitem_paid_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialorder',
            name='order_month',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_month',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_year',
        ),
        migrations.AddField(
            model_name='materialorder',
            name='ordered_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='주문일자'),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='expected_date',
            field=models.DateField(blank=True, null=True, verbose_name='예상 입고일'),
        ),
    ]
