# Generated by Django 5.1.5 on 2025-09-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0020_remove_materialorder_order_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrelease',
            name='tax_invoice_sent',
            field=models.BooleanField(default=False, verbose_name='세금계산서 발행 여부'),
        ),
    ]
