# Generated by Django 5.1.5 on 2025-09-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0021_materialrelease_tax_invoice_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='정렬순서'),
        ),
    ]
