# Generated by Django 5.1.5 on 2025-09-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0022_material_display_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['vendor', 'vendor_order', 'name']},
        ),
        migrations.RemoveField(
            model_name='material',
            name='display_order',
        ),
        migrations.AddField(
            model_name='material',
            name='vendor_order',
            field=models.PositiveIntegerField(default=0, verbose_name='거래처 내 순서'),
        ),
    ]
