# Generated by Django 5.1.5 on 2025-09-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0023_alter_material_options_remove_material_display_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrelease',
            name='notes',
            field=models.TextField(blank=True, verbose_name='비고'),
        ),
        migrations.AddField(
            model_name='materialrelease',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='견적서 제목'),
        ),
        migrations.AddField(
            model_name='materialreleaseitem',
            name='included',
            field=models.BooleanField(default=True, verbose_name='견적 포함 여부'),
        ),
    ]
