# Generated by Django 5.1.5 on 2025-09-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0024_materialrelease_notes_materialrelease_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialreleaseitem',
            name='group_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='품명(묶음표시)'),
        ),
    ]
