# Generated by Django 5.1.5 on 2025-09-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0026_materialorderitem_receive_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialorderitem',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='비고'),
        ),
    ]
