# Generated by Django 5.1.5 on 2025-09-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0027_materialorderitem_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialorder',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='비고'),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='receive_type',
            field=models.CharField(choices=[('order', '주문입고'), ('return', '반납입고')], default='order', max_length=10, verbose_name='입고 종류'),
        ),
    ]
