# Generated by Django 5.1.5 on 2025-09-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0028_materialorder_notes_materialorder_receive_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrelease',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='수금일'),
        ),
    ]
