# Generated by Django 4.2.29 on 2026-05-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0032_materialrelease_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrelease',
            name='request_sent',
            field=models.BooleanField(default=False, verbose_name='출고 요청 알림 발송 여부'),
        ),
    ]
