# Generated by Django 4.2.29 on 2026-05-20 08:23

from django.db import migrations, models


def backfill_released_quantity(apps, schema_editor):
    MaterialReleaseItem = apps.get_model('materials', 'MaterialReleaseItem')
    MaterialReleaseItem.objects.filter(status='released').update(
        released_quantity=models.F('quantity')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0033_materialrelease_request_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialreleaseitem',
            name='released_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='실출고수량'),
        ),
        migrations.RunPython(backfill_released_quantity, migrations.RunPython.noop),
    ]
