# Generated by Django 5.1.5 on 2026-06-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0034_released_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialorder',
            name='release_location',
            field=models.CharField(blank=True, default='메듀랩', max_length=100, verbose_name='출고장소'),
        ),
    ]
