# Generated by Django 5.1.5 on 2025-09-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto_predictor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_no', models.IntegerField()),
                ('numbers', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
