# Generated by Django 5.1.5 on 2025-09-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto_predictor', '0002_recommendedset'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedset',
            name='strategy',
            field=models.CharField(default='freq', max_length=20),
        ),
    ]
