# Generated by Django 5.1.5 on 2025-09-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_withdrawal_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('parent', '학부모'), ('student', '학생'), ('pre_teacher', '예비강사'), ('teacher', '강사')], default='parent', max_length=20),
        ),
    ]
