# Generated by Django 5.1.5 on 2025-09-03 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_user_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('parent', '학부모'), ('student', '학생'), ('pre_teacher', '예비강사'), ('teacher', '강사'), ('institution', '기관')], default='parent', max_length=20),
        ),
        migrations.CreateModel(
            name='InstitutionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=120, verbose_name='기관명')),
                ('business_number', models.CharField(blank=True, max_length=30, verbose_name='사업자등록번호')),
                ('contact_name', models.CharField(max_length=60, verbose_name='담당자명')),
                ('phone_number', models.CharField(max_length=30, verbose_name='전화번호')),
                ('postcode', models.CharField(blank=True, max_length=16, verbose_name='우편번호')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='주소')),
                ('detail_address', models.CharField(blank=True, max_length=255, verbose_name='상세주소')),
                ('industry', models.CharField(blank=True, max_length=60, verbose_name='업종')),
                ('website', models.URLField(blank=True, verbose_name='홈페이지')),
                ('fax', models.CharField(blank=True, max_length=30, verbose_name='팩스')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institution_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
