# Generated by Django 5.1.5 on 2025-09-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_user_type_institutionprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionprofile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='담당자 휴대폰 번호'),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='office_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='기관 전화번호'),
        ),
    ]
