# Generated by Django 5.1.5 on 2025-09-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('parent', '학부모'), ('student', '학생'), ('pre_teacher', '예비강사'), ('teacher', '강사'), ('center_teacher', '센터강사'), ('institution', '기관')], default='parent', max_length=20),
        ),
    ]
