# Generated by Django 5.1.5 on 2026-01-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('student', '학생'), ('parent', '학부모'), ('pre_teacher', '예비강사'), ('teacher', '강사'), ('center_teacher', '센터강사'), ('institution', '기관')], default='parent', max_length=20),
        ),
    ]
