# Generated by Django 5.1.5 on 2026-01-07 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='student_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_student', to='accounts.profile', verbose_name='학생 계정'),
        ),
    ]
