# Generated by Django 4.2.29 on 2026-05-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_child_student_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='kakao_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
