# Generated by Django 4.2.29 on 2026-05-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_kakao_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='kakao_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
