# Generated by Django 5.1.5 on 2025-07-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachinginstitution',
            name='day',
            field=models.CharField(choices=[('월', '월요일'), ('화', '화요일'), ('수', '수요일'), ('목', '목요일'), ('금', '금요일'), ('토', '토요일'), ('일', '일요일')], default='월', max_length=10),
        ),
        migrations.AlterField(
            model_name='teachinginstitution',
            name='program',
            field=models.CharField(max_length=100),
        ),
    ]
