# Generated by Django 5.1.5 on 2025-07-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teachinginstitution_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='teachinginstitution',
            name='day',
        ),
        migrations.AddField(
            model_name='teachinginstitution',
            name='days',
            field=models.ManyToManyField(to='teachers.teachingday'),
        ),
    ]
