# Generated by Django 5.1.5 on 2025-08-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teachingday_remove_teachinginstitution_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachinginstitution',
            name='admin_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='행정실 이메일'),
        ),
        migrations.AddField(
            model_name='teachinginstitution',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='담당자 이메일'),
        ),
    ]
