# Generated by Django 5.1.5 on 2025-08-19 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_career_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='career',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='세부내용'),
        ),
        migrations.AlterField(
            model_name='career',
            name='organization',
            field=models.CharField(default='기관명 미입력', max_length=200, verbose_name='기관명'),
        ),
        migrations.AlterField(
            model_name='career',
            name='position',
            field=models.CharField(default='직책 미입력', max_length=100, verbose_name='직책'),
        ),
        migrations.AlterField(
            model_name='career',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='시작일'),
        ),
    ]
