# Generated by Django 5.1.5 on 2025-12-16 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_alter_school_student_count'),
        ('teachers', '0007_career_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachinginstitution',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_institutions', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='teachinginstitution',
            name='admin_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='teachinginstitution',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
