# Generated by Django 5.1.5 on 2025-12-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_teachinginstitution_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachinginstitution',
            name='place_type',
            field=models.CharField(choices=[('school', '학교'), ('kindergarten', '유치원'), ('child_center', '지역아동센터'), ('culture_center', '문화센터'), ('other', '기타 기관')], default='school', max_length=20, verbose_name='출강 장소 유형'),
        ),
    ]
