# Generated by Django 5.1.5 on 2026-03-25 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_teachinginstitution_place_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachinginstitution',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachinginstitution',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
