# Generated by Django 5.1.5 on 2026-07-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0010_teachinginstitution_closed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateCatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='종류')),
                ('auth_type', models.CharField(help_text='예: 민간, 국가공인', max_length=50, verbose_name='인증')),
                ('name', models.CharField(max_length=200, verbose_name='자격증명')),
                ('issuer', models.CharField(blank=True, max_length=200, verbose_name='발행처')),
                ('validity', models.CharField(blank=True, max_length=100, verbose_name='유효기간')),
                ('issue_fee', models.CharField(blank=True, max_length=100, verbose_name='발급비')),
                ('education_fee', models.CharField(blank=True, max_length=100, verbose_name='교육비')),
                ('materials', models.CharField(blank=True, max_length=200, verbose_name='교구재')),
                ('min_students', models.CharField(blank=True, max_length=100, verbose_name='최소수강인원')),
                ('session_length', models.CharField(blank=True, max_length=50, verbose_name='1차시 시간')),
                ('session_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='교육차시')),
                ('curriculum', models.TextField(blank=True, help_text='한 줄에 한 차시씩 입력', verbose_name='차시별 커리큘럼')),
                ('exam_type', models.CharField(blank=True, max_length=200, verbose_name='시험형태')),
                ('exam_fee', models.CharField(blank=True, max_length=100, verbose_name='시험비')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='표시 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
