# Generated by Django 5.1.5 on 2026-07-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0012_seed_certificate_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatecatalogitem',
            name='related_link',
            field=models.URLField(blank=True, max_length=500, verbose_name='관련링크'),
        ),
    ]
