# Generated by Django 5.1.5 on 2026-07-22 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0019_instructorrecruit_class_days_and_more'),
        ('teachers', '0013_certificatecatalogitem_related_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatecatalogitem',
            name='related_recruit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_items', to='recruit.instructorrecruit', verbose_name='연결된 교육과정(모집공고)'),
        ),
    ]
