# Generated by Django 5.1.5 on 2026-07-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0016_normalize_auth_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatecatalogitem',
            name='course_intro',
            field=models.TextField(blank=True, verbose_name='과정 소개'),
        ),
        migrations.AddField(
            model_name='certificatecatalogitem',
            name='educational_goal',
            field=models.TextField(blank=True, verbose_name='교육 목표'),
        ),
    ]
