# Generated by Django 5.1.5 on 2025-08-14 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('audience', models.CharField(choices=[('all', '전체'), ('parent', '학부모'), ('student', '학생'), ('teacher', '강사')], db_index=True, default='all', max_length=10, verbose_name='대상')),
                ('status', models.CharField(choices=[('draft', '임시저장'), ('published', '게시')], db_index=True, default='published', max_length=10, verbose_name='상태')),
                ('is_pinned', models.BooleanField(db_index=True, default=False, verbose_name='상단 고정')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notices/%Y/%m/', verbose_name='첨부파일')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='게시일')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'ordering': ['-is_pinned', '-published_at'],
            },
        ),
    ]
