# Generated by Django 4.2.29 on 2026-04-27 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='메뉴 제목')),
                ('url', models.CharField(blank=True, default='#', max_length=255, verbose_name='이동 URL/뷰이름')),
                ('icon_class', models.CharField(blank=True, help_text='예: bi-gear, bi-people', max_length=100, verbose_name='아이콘 클래스')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='출력 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 상태')),
                ('access_level', models.CharField(choices=[('all', '누구나'), ('guest', '비로그인 사용자'), ('authenticated', '로그인한 모든 사용자'), ('staff', '관리자(Staff)'), ('teacher', '강사'), ('institution', '기관'), ('parent', '학부모')], default='staff', max_length=20, verbose_name='접근 권한')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_menus', to='main.menuitem', verbose_name='상위 메뉴')),
            ],
            options={
                'verbose_name': '메뉴 항목',
                'verbose_name_plural': '메뉴 항목들',
                'ordering': ['order', 'id'],
            },
        ),
    ]
