# Generated by Django 4.2.29 on 2026-04-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='access_level',
            field=models.CharField(choices=[('all', '누구나'), ('teacher', '강사용'), ('institution', '기관용'), ('staff', '관리자용')], default='staff', max_length=20, verbose_name='접근 권한'),
        ),
    ]
