# Generated by Django 5.1.5 on 2025-09-02 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='프로그램명')),
                ('target', models.CharField(choices=[('kid', '유아'), ('elem', '초등'), ('mid', '중등'), ('high', '고등'), ('adult', '성인')], max_length=20, verbose_name='대상')),
                ('recruit_start_date', models.DateField(blank=True, null=True, verbose_name='모집 시작일')),
                ('recruit_end_date', models.DateField(blank=True, null=True, verbose_name='모집 마감일')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='수업 시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='수업 종료일')),
                ('class_days', models.CharField(blank=True, help_text='쉼표로 구분된 요일 저장 (예: mon,tue,fri)', max_length=50, null=True, verbose_name='수업요일')),
                ('class_time_start', models.TimeField(blank=True, null=True, verbose_name='수업 시작시간')),
                ('class_time_end', models.TimeField(blank=True, null=True, verbose_name='수업 종료시간')),
                ('capacity', models.PositiveIntegerField(default=10, verbose_name='정원')),
                ('session_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='수업횟수')),
                ('tuition', models.PositiveIntegerField(blank=True, null=True, verbose_name='수업료(원)')),
                ('description', models.TextField(blank=True, verbose_name='상세내용')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='대표이미지')),
                ('status', models.CharField(choices=[('open', '모집중'), ('closed', '모집마감'), ('hidden', '비공개')], default='open', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=100, verbose_name='신청자명')),
                ('phone', models.CharField(max_length=30, verbose_name='연락처')),
                ('memo', models.CharField(blank=True, max_length=300, verbose_name='요청사항(선택)')),
                ('status', models.CharField(choices=[('pending', '신청접수'), ('approved', '승인'), ('rejected', '반려'), ('cancelled', '취소')], default='pending', max_length=20, verbose_name='상태')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_applications', to='accounts.profile')),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='accounts.child')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='courses.program')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('program', 'child')},
            },
        ),
    ]
