# Generated by Django 5.1.5 on 2025-09-02 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_withdrawal_requested'),
        ('courses', '0002_add_child_field_to_programapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programapplication',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='accounts.child'),
        ),
    ]
