# Generated by Django 5.1.5 on 2025-09-02 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_add_applicant_field_to_programapplication'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DROP INDEX IF EXISTS courses_programapplication_program_id_user_id_3341ce16_uniq;
                DROP INDEX IF EXISTS courses_programapplication_user_id_4c326adb;
                ALTER TABLE courses_programapplication DROP COLUMN user_id;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
