# Generated by Django 5.1.5 on 2025-09-02 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_withdrawal_requested'),
        ('courses', '0005_drop_user_id_and_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programapplication',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_applications', to='accounts.profile'),
        ),
    ]
