# Generated by Django 5.1.5 on 2025-09-04 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_programapplication_applicant'),
        ('teachers', '0007_career_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='상품명')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='카테고리')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='수업시간(분)')),
                ('base_price', models.PositiveIntegerField(default=0, verbose_name='기본 가격(원)')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='수업 날짜')),
                ('start_time', models.TimeField(verbose_name='시작 시간')),
                ('end_time', models.TimeField(verbose_name='종료 시간')),
                ('headcount', models.PositiveIntegerField(default=10, verbose_name='예상 인원')),
                ('place', models.CharField(blank=True, max_length=200, verbose_name='수업 장소')),
                ('memo', models.TextField(blank=True, verbose_name='요청 메모')),
                ('status', models.CharField(choices=[('requested', '예약요청'), ('approved', '승인'), ('rejected', '반려'), ('canceled', '취소')], default='requested', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='teachers.teachinginstitution', verbose_name='기관')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='요청자')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='courses.programproduct', verbose_name='프로그램 상품')),
            ],
            options={
                'ordering': ['-date', 'start_time'],
            },
        ),
    ]
