# Generated by Django 5.1.5 on 2025-09-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_programproduct_institutionreservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리',
            },
        ),
        migrations.AddField(
            model_name='programproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='프로그램 이미지'),
        ),
        migrations.AddField(
            model_name='programproduct',
            name='topics',
            field=models.JSONField(blank=True, default=list, verbose_name='주제'),
        ),
    ]
