# Generated by Django 5.1.5 on 2025-09-08 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_category_programproduct_image_programproduct_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.category'),
        ),
    ]
