# Generated by Django 5.1.5 on 2025-09-08 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_programproduct_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programproduct',
            name='category',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.category'),
        ),
    ]
