# Generated by Django 5.1.5 on 2025-09-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_institutionreservation_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionreservation',
            name='status',
            field=models.CharField(choices=[('requested', '예약요청'), ('approved', '예약확정'), ('canceled', '예약취소')], default='requested', max_length=20, verbose_name='상태'),
        ),
    ]
