# Generated by Django 5.1.5 on 2025-09-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_institutionreservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionreservation',
            name='selected_topic',
            field=models.CharField(blank=True, max_length=200, verbose_name='선택 주제'),
        ),
    ]
