# Generated by Django 5.1.5 on 2025-09-15 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_institutionreservation_selected_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__user_type': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='담당 강사'),
        ),
    ]
