# Generated by Django 5.1.5 on 2025-09-15 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_birth_date'),
        ('courses', '0015_alter_program_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile', verbose_name='담당 강사'),
        ),
    ]
