# Generated by Django 5.1.5 on 2025-09-15 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_program_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='tuition',
            field=models.PositiveIntegerField(blank=True, default=120000, null=True, verbose_name='수업료(원)'),
        ),
    ]
