# Generated by Django 5.1.5 on 2025-09-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_program_tuition'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='class_duration',
            field=models.PositiveIntegerField(default=60, help_text='분 단위로 입력하세요', verbose_name='수업시간(분)'),
        ),
    ]
