# Generated by Django 5.1.5 on 2025-09-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_migrate_program_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='target',
        ),
        migrations.AddField(
            model_name='program',
            name='targets',
            field=models.ManyToManyField(blank=True, related_name='programs', to='courses.target'),
        ),
    ]
