# Generated by Django 5.1.5 on 2025-09-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_remove_program_target_program_targets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='target',
            options={'ordering': ['id'], 'verbose_name': '대상', 'verbose_name_plural': '대상 목록'},
        ),
        migrations.AlterField(
            model_name='target',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
