# Generated by Django 5.1.5 on 2025-09-15 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_alter_target_options_alter_target_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='targets',
        ),
        migrations.AddField(
            model_name='program',
            name='target_end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programs_end', to='courses.target'),
        ),
        migrations.AddField(
            model_name='program',
            name='target_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programs_start', to='courses.target'),
        ),
    ]
