# Generated by Django 5.1.5 on 2025-09-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_remove_program_targets_program_target_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='products/', verbose_name='프로그램 이미지'),
        ),
    ]
