# Generated by Django 5.1.5 on 2025-09-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_alter_programproduct_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': '프로그램 유형',
                'verbose_name_plural': '프로그램 유형 목록',
            },
        ),
        migrations.AddField(
            model_name='program',
            name='material',
            field=models.CharField(blank=True, help_text='예: 없음, 대여, 보유', max_length=100),
        ),
        migrations.AlterField(
            model_name='programproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='프로그램 이미지'),
        ),
        migrations.AddField(
            model_name='program',
            name='program_types',
            field=models.ManyToManyField(blank=True, to='courses.programtype'),
        ),
    ]
