# Generated by Django 5.1.5 on 2025-09-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_programtype_program_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='status',
            field=models.CharField(choices=[('open', '모집중'), ('closed', '모집마감'), ('hidden', '비공개')], default='hidden', max_length=20, verbose_name='상태'),
        ),
    ]
