# Generated by Django 5.1.5 on 2025-09-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_alter_program_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='programproduct',
            name='status',
            field=models.CharField(choices=[('public', '공개'), ('private', '비공개')], default='private', max_length=20, verbose_name='공개 상태'),
        ),
    ]
