# Generated by Django 5.1.5 on 2025-09-16 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_programproduct_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programproduct',
            name='is_active',
        ),
    ]
