# Generated by Django 5.1.5 on 2025-09-16 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_remove_programproduct_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='programproduct',
            name='include_material_cost',
            field=models.BooleanField(default=True, verbose_name='재료비 포함 여부'),
        ),
        migrations.AddField(
            model_name='programproduct',
            name='included_materials',
            field=models.TextField(blank=True, verbose_name='포함 재료 설명'),
        ),
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='재료명')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='가격(원)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.programproduct')),
            ],
        ),
    ]
