# Generated by Django 5.1.5 on 2025-09-27 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_programproduct_include_material_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='반 이름')),
                ('day', models.CharField(choices=[('mon', '월'), ('tue', '화'), ('wed', '수'), ('thu', '목'), ('fri', '금'), ('sat', '토'), ('sun', '일')], max_length=10, verbose_name='요일')),
                ('start_time', models.TimeField(verbose_name='시작 시간')),
                ('end_time', models.TimeField(verbose_name='종료 시간')),
                ('start_date', models.DateField(verbose_name='수업 시작일')),
                ('end_date', models.DateField(verbose_name='수업 종료일')),
                ('session_count', models.PositiveIntegerField(default=0, verbose_name='총 수업횟수')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='순서')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='courses.program')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
