# Generated by Django 5.1.5 on 2025-09-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_programclass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programclass',
            options={},
        ),
        migrations.RemoveField(
            model_name='programclass',
            name='day',
        ),
        migrations.RemoveField(
            model_name='programclass',
            name='session_count',
        ),
        migrations.AddField(
            model_name='programclass',
            name='days',
            field=models.JSONField(blank=True, default=list, verbose_name='요일들'),
        ),
    ]
