# Generated by Django 5.1.5 on 2025-09-27 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_alter_programclass_options_remove_programclass_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='class_time_end',
        ),
        migrations.RemoveField(
            model_name='program',
            name='class_time_start',
        ),
        migrations.RemoveField(
            model_name='program',
            name='end_date',
        ),
    ]
