# Generated by Django 5.1.5 on 2025-09-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_remove_program_class_time_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='수업 종료일'),
        ),
    ]
