# Generated by Django 5.1.5 on 2025-09-28 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_alter_programapplication_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='programapplication',
            name='unique_program_class_child',
        ),
    ]
