# Generated by Django 5.1.5 on 2025-09-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_add_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='programclass',
            name='capacity',
            field=models.PositiveIntegerField(default=0, verbose_name='정원'),
        ),
    ]
