# Generated by Django 5.1.5 on 2025-09-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_programclass_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programclass',
            name='capacity',
            field=models.PositiveIntegerField(default=10, verbose_name='정원'),
        ),
    ]
