# Generated by Django 5.1.5 on 2025-09-28 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_alter_programclass_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='capacity',
        ),
    ]
