# Generated by Django 5.1.5 on 2025-09-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0041_remove_program_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='기준 나이'),
        ),
    ]
