# Generated by Django 5.1.5 on 2025-09-29 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0042_target_age'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='programapplication',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='program',
            name='class_days',
        ),
    ]
