# Generated by Django 5.1.5 on 2025-09-30 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0043_alter_programapplication_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programclass',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='수업 종료일'),
        ),
    ]
