# Generated by Django 5.1.5 on 2025-09-30 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_user_type'),
        ('courses', '0044_alter_programclass_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'center_teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile', verbose_name='담당 강사'),
        ),
    ]
