# Generated by Django 5.1.5 on 2025-10-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0045_alter_program_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='monthly_sessions',
            field=models.PositiveIntegerField(default=0, verbose_name='월 횟수'),
        ),
        migrations.AddField(
            model_name='program',
            name='months',
            field=models.PositiveIntegerField(default=0, verbose_name='개월 과정'),
        ),
        migrations.AddField(
            model_name='program',
            name='weekly_sessions',
            field=models.PositiveIntegerField(default=0, verbose_name='주 횟수'),
        ),
    ]
