# Generated by Django 5.1.5 on 2025-10-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0046_program_monthly_sessions_program_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='base_fee',
            field=models.PositiveIntegerField(default=0, verbose_name='강사료'),
        ),
        migrations.AddField(
            model_name='program',
            name='include_materials',
            field=models.BooleanField(default=False, verbose_name='교구재 포함'),
        ),
        migrations.AddField(
            model_name='program',
            name='material_fee',
            field=models.PositiveIntegerField(default=0, verbose_name='교구비'),
        ),
        migrations.AlterField(
            model_name='program',
            name='tuition',
            field=models.PositiveIntegerField(blank=True, default=120000, null=True, verbose_name='수강료(월)'),
        ),
    ]
