# Generated by Django 5.1.5 on 2025-11-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0047_program_base_fee_program_include_materials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='recruit_type',
            field=models.CharField(blank=True, choices=[('always', '상시모집'), ('event', '이벤트'), ('short', '단기수업')], default='always', max_length=20, null=True),
        ),
    ]
