# Generated by Django 5.1.5 on 2025-11-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0048_program_recruit_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programtype',
            options={'ordering': ['order', 'name'], 'verbose_name': '프로그램 유형', 'verbose_name_plural': '프로그램 유형 목록'},
        ),
        migrations.AddField(
            model_name='programtype',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
