# Generated by Django 5.1.5 on 2025-11-26 03:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0050_learningprogram_enrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enrollment',
            new_name='LearningEnrollment',
        ),
        migrations.RenameField(
            model_name='learningenrollment',
            old_name='created_at',
            new_name='enrolled_at',
        ),
        migrations.AlterUniqueTogether(
            name='learningenrollment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='learningprogram',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
