# Generated by Django 5.1.5 on 2025-11-27 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0053_userprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningprogram',
            name='code',
        ),
    ]
