# Generated by Django 5.1.5 on 2025-11-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0054_remove_learningprogram_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
