# Generated by Django 5.1.5 on 2025-12-06 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0055_chapter_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningprogram',
            name='program_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_programs', to='courses.programtype', verbose_name='프로그램 유형'),
        ),
    ]
