# Generated by Django 5.1.5 on 2025-12-15 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0056_learningprogram_program_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramSyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveIntegerField(verbose_name='차시')),
                ('title', models.CharField(max_length=200, verbose_name='수업 주제')),
                ('content', models.TextField(verbose_name='수업 내용')),
                ('material', models.CharField(blank=True, max_length=200, verbose_name='준비물')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='비고')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='courses.program')),
            ],
            options={
                'ordering': ['week'],
            },
        ),
    ]
