# Generated by Django 5.1.5 on 2025-12-15 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0057_programsyllabus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='커리큘럼명')),
                ('description', models.TextField(blank=True, verbose_name='커리큘럼 소개')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_end', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='curriculums_end', to='courses.target')),
                ('target_start', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='curriculums_start', to='courses.target')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='courses.curriculum', verbose_name='연결 커리큘럼'),
        ),
        migrations.CreateModel(
            name='CurriculumSyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveIntegerField(verbose_name='차시')),
                ('title', models.CharField(max_length=200, verbose_name='수업 주제')),
                ('content', models.TextField(verbose_name='수업 내용')),
                ('material', models.CharField(blank=True, max_length=200, verbose_name='준비물')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='courses.curriculum')),
            ],
            options={
                'ordering': ['week'],
            },
        ),
    ]
