# Generated by Django 5.1.5 on 2025-12-15 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0058_curriculum_program_curriculum_curriculumsyllabus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculumsyllabus',
            name='curriculum',
        ),
        migrations.RemoveField(
            model_name='program',
            name='curriculum',
        ),
        migrations.CreateModel(
            name='CurriculumProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='커리큘럼 프로그램명')),
                ('description', models.TextField(blank=True, verbose_name='프로그램 소개')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_end', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_programs_end', to='courses.target')),
                ('target_start', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_programs_start', to='courses.target')),
            ],
        ),
        migrations.AddField(
            model_name='curriculumsyllabus',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='courses.curriculumprogram'),
        ),
        migrations.AddField(
            model_name='program',
            name='curriculum_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='courses.curriculumprogram', verbose_name='연결 커리큘럼 프로그램'),
        ),
        migrations.DeleteModel(
            name='Curriculum',
        ),
    ]
