# Generated by Django 5.1.5 on 2026-01-07 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_user_type'),
        ('courses', '0059_remove_curriculumsyllabus_curriculum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('is_active', models.BooleanField(default=True, verbose_name='수강중')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.program', verbose_name='프로그램')),
                ('program_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.programclass', verbose_name='반')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_enrollments', to='accounts.child', verbose_name='학생')),
            ],
            options={
                'verbose_name': '프로그램 수강생',
                'verbose_name_plural': '프로그램 수강생 목록',
                'unique_together': {('program_class', 'student')},
            },
        ),
    ]
