# Generated by Django 5.1.5 on 2026-01-07 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_user_type'),
        ('courses', '0060_programenrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programenrollment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='program_enrollments', to='accounts.profile', verbose_name='학생(회원)'),
        ),
    ]
