# Generated by Django 5.1.5 on 2026-02-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0061_alter_programenrollment_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumprogram',
            name='class_type',
            field=models.CharField(blank=True, choices=[('offline', '오프라인'), ('online', '온라인'), ('hybrid', '하이브리드')], max_length=20, verbose_name='수업 유형'),
        ),
        migrations.AddField(
            model_name='curriculumprogram',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('beginner', '입문'), ('intermediate', '중급'), ('advanced', '고급')], max_length=20, verbose_name='난이도'),
        ),
        migrations.AddField(
            model_name='curriculumprogram',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='분 단위', null=True, verbose_name='수업시간(분)'),
        ),
        migrations.AddField(
            model_name='curriculumprogram',
            name='duration_period',
            field=models.CharField(blank=True, help_text='예: 12주, 1개월', max_length=100, verbose_name='수업기간'),
        ),
    ]
