# Generated by Django 5.1.5 on 2026-02-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0062_curriculumprogram_class_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='수업 분야명')),
            ],
            options={
                'verbose_name': '수업 분야',
                'verbose_name_plural': '수업 분야 목록',
            },
        ),
        migrations.AlterField(
            model_name='curriculumprogram',
            name='class_type',
            field=models.CharField(blank=True, choices=[('정규반', '정규반'), ('단기특강', '단기특강'), ('체험형', '체험형')], max_length=20, verbose_name='수업 유형'),
        ),
        migrations.AlterField(
            model_name='curriculumprogram',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('intro', '입문'), ('basic', '기초'), ('intermediate', '중급'), ('advanced', '심화')], max_length=20, verbose_name='난이도'),
        ),
        migrations.AddField(
            model_name='curriculumprogram',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='courses.subject', verbose_name='수업 분야'),
        ),
    ]
