# Generated by Django 5.1.5 on 2026-02-02 08:02

from django.db import migrations

def create_subjects(apps, schema_editor):
    Subject = apps.get_model('courses', 'Subject')
    subjects = [
        "로봇", "코딩", "AI", "과학", "수학", "3D펜"
    ]
    for subject_name in subjects:
        Subject.objects.create(name=subject_name)

class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0063_subject_alter_curriculumprogram_class_type_and_more'),
    ]

    operations = [
        migrations.RunPython(create_subjects),
    ]
