# Generated by Django 5.1.5 on 2025-10-29 15:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='업무 제목')),
                ('description', models.TextField(blank=True, verbose_name='내용')),
                ('work_type', models.CharField(choices=[('personal', '개인'), ('school', '학교'), ('academy', '학원'), ('other', '기타')], default='personal', max_length=20, verbose_name='업무 종류')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='작성일자')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='마감일자')),
                ('completed', models.BooleanField(default=False, verbose_name='완료 여부')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='종료일자')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
    ]
