# Generated by Django 5.1.5 on 2025-10-29 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='업무종류명')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='표시순서')),
            ],
            options={
                'verbose_name': '업무 종류',
                'verbose_name_plural': '업무 종류 목록',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.worktype', verbose_name='업무 종류'),
        ),
    ]
