# Generated by Django 5.1.5 on 2025-11-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_worktype_alter_task_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='repeat',
            field=models.CharField(choices=[('none', '반복 없음'), ('daily', '매일'), ('weekly', '매주'), ('monthly', '매월'), ('yearly', '매년')], default='none', help_text='업무가 반복되는 주기를 설정합니다.', max_length=10, verbose_name='반복 주기'),
        ),
    ]
