# Generated by Django 5.1.5 on 2025-12-13 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='사이트명')),
                ('url', models.URLField(verbose_name='목록 URL')),
                ('active', models.BooleanField(default=True, verbose_name='사용 여부')),
                ('request_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='GET', max_length=10, verbose_name='요청 방식')),
                ('extra_params', models.JSONField(blank=True, help_text='POST 또는 GET으로 함께 전송할 파라미터 (dict 형태)', null=True, verbose_name='추가 파라미터')),
                ('list_selector', models.CharField(help_text='게시글 목록 CSS Selector', max_length=200, verbose_name='목록 셀렉터')),
                ('title_selector', models.CharField(max_length=200, verbose_name='제목 셀렉터')),
                ('link_selector', models.CharField(max_length=200, verbose_name='링크 셀렉터')),
                ('date_selector', models.CharField(blank=True, max_length=200, verbose_name='날짜 셀렉터')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollectedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('link', models.URLField()),
                ('post_date', models.CharField(blank=True, max_length=50)),
                ('is_new', models.BooleanField(default=True)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='linkhub.sourcesite')),
            ],
            options={
                'ordering': ['-collected_at'],
                'unique_together': {('source', 'link')},
            },
        ),
    ]
