# Generated by Django 5.1.5 on 2025-12-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkhub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectedpost',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='지역'),
        ),
        migrations.AddField(
            model_name='collectedpost',
            name='school_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='학교명'),
        ),
    ]
