# Generated by Django 5.1.5 on 2025-12-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkhub', '0002_collectedpost_region_collectedpost_school_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collectedpost',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='collectedpost',
            name='mng_no',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='공고 관리번호'),
        ),
        migrations.AlterUniqueTogether(
            name='collectedpost',
            unique_together={('source', 'mng_no')},
        ),
    ]
