# Generated by Django 5.1.5 on 2025-12-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkhub', '0003_alter_collectedpost_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectedpost',
            name='status',
            field=models.CharField(blank=True, help_text='모집중 / 마감 등', max_length=30, verbose_name='상태'),
        ),
    ]
