# Generated by Django 5.1.5 on 2025-12-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkhub', '0004_collectedpost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcesite',
            name='collector',
            field=models.CharField(choices=[('NEULBOM', '늘봄허브'), ('JNE_COMMON', '전남교육청 공통'), ('JNE_REGION', '전남교육청 지역형')], default='NEULBOM', max_length=30),
            preserve_default=False,
        ),
    ]
