# Generated by Django 5.1.5 on 2025-12-13 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkhub', '0005_sourcesite_collector'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectedpost',
            options={'ordering': ['collected_at']},
        ),
    ]
