# Generated by Django 5.1.5 on 2025-12-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkhub', '0006_alter_collectedpost_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectedpost',
            options={'ordering': ['-collected_at']},
        ),
        migrations.AddField(
            model_name='collectedpost',
            name='attachment_urls',
            field=models.JSONField(blank=True, default=list, help_text='[{"name": "...", "url": "..."}]', verbose_name='첨부파일 URL 목록'),
        ),
        migrations.AddField(
            model_name='collectedpost',
            name='weekday',
            field=models.CharField(blank=True, help_text='예: 월, 수, 금', max_length=50, verbose_name='운영요일'),
        ),
        migrations.AlterField(
            model_name='collectedpost',
            name='status',
            field=models.CharField(blank=True, help_text='모집중 / 마감 등 (자동 계산)', max_length=30, verbose_name='상태'),
        ),
    ]
