# Generated by Django 5.1.5 on 2025-12-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkhub', '0007_alter_collectedpost_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcesite',
            name='area',
            field=models.CharField(choices=[('GWANGJU', '광주'), ('JEONNAM', '전남')], db_index=True, default='GWANGJU', help_text='광주 / 전남 구분', max_length=10, verbose_name='관리 지역'),
        ),
    ]
