# Generated by Django 5.1.5 on 2025-12-31 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkhub', '0008_sourcesite_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeulbomConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff_date', models.DateField(verbose_name='늘봄 수집 기준 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
