# Generated by Django 5.1.5 on 2026-05-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkhub', '0009_neulbomconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkhubConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_collect', models.BooleanField(default=False, verbose_name='자동수집 ON/OFF')),
                ('expire_deadline_days', models.PositiveIntegerField(default=3, verbose_name='마감 후 삭제 기준(일)')),
                ('expire_no_deadline_days', models.PositiveIntegerField(default=30, verbose_name='등록일 기준 삭제(일, 마감일 없는 공고)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'linkhub 설정',
            },
        ),
    ]
