# Generated by Django 5.1.5 on 2025-12-27 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypingStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='단계명')),
                ('stage_type', models.CharField(choices=[('POSITION', '자리연습'), ('WORD', '낱말연습'), ('SENTENCE', '단문연습'), ('PARAGRAPH', '장문연습')], max_length=20, verbose_name='연습 유형')),
                ('min_speed', models.IntegerField(default=0, verbose_name='최소 타수')),
                ('min_accuracy', models.IntegerField(default=0, verbose_name='최소 정확도(%)')),
                ('max_typo', models.IntegerField(default=999, verbose_name='허용 오타 수')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='단계 순서')),
            ],
        ),
        migrations.CreateModel(
            name='TypingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.IntegerField(verbose_name='타수(타/분)')),
                ('accuracy', models.FloatField(verbose_name='정확도')),
                ('typo_count', models.IntegerField(verbose_name='오타 수')),
                ('duration', models.IntegerField(verbose_name='진행 시간(초)')),
                ('passed', models.BooleanField(default=False, verbose_name='통과 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typing_trainer.typingstage')),
            ],
        ),
    ]
