# Generated by Django 5.1.5 on 2025-12-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_trainer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typingstage',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=60, verbose_name='연습 시간(초)'),
        ),
        migrations.AddField(
            model_name='typingstage',
            name='language',
            field=models.CharField(choices=[('KO', '한글'), ('EN', '영어')], default='KO', max_length=2, verbose_name='언어'),
        ),
        migrations.AddField(
            model_name='typingstage',
            name='practice_chars',
            field=models.TextField(blank=True, help_text='예: ㅁ,ㄴ,ㅇ,ㄹ 또는 a,s,d,f', verbose_name='연습 문자(쉼표로 구분)'),
        ),
    ]
