# Generated by Django 5.1.5 on 2025-12-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_count', models.CharField(blank=True, max_length=50)),
                ('homepage', models.URLField(blank=True)),
                ('zipcode', models.CharField(blank=True, max_length=10)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('office_phone', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
