# Generated by Django 5.1.5 on 2025-12-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_alter_school_address_alter_school_homepage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='student_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
