# Generated by Django 5.1.5 on 2025-12-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_school_school_code_alter_school_student_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='student_count',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
