# Generated by Django 5.1.5 on 2025-12-10 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('진행', '진행'), ('마감', '마감')], default='진행', max_length=10)),
                ('receive_date', models.DateField()),
                ('deadline', models.DateTimeField()),
                ('submit_method', models.CharField(choices=[('방문', '방문'), ('우편', '우편'), ('메일', '메일')], max_length=20)),
                ('region', models.CharField(max_length=30)),
                ('school_name', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=50)),
                ('student_count', models.CharField(blank=True, max_length=20)),
                ('fee_type', models.CharField(max_length=20)),
                ('fee_amount', models.PositiveIntegerField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='recruit_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-receive_date'],
            },
        ),
    ]
