# Generated by Django 5.1.5 on 2025-12-10 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruitnotice',
            options={},
        ),
        migrations.RemoveField(
            model_name='recruitnotice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='recruitnotice',
            name='school_name',
        ),
        migrations.AddField(
            model_name='recruitnotice',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.school'),
        ),
        migrations.AlterField(
            model_name='recruitnotice',
            name='submit_method',
            field=models.CharField(choices=[('늘봄허브', '늘봄허브'), ('방문', '방문'), ('우편', '우편'), ('메일', '메일')], max_length=20),
        ),
    ]
