# Generated by Django 5.1.5 on 2025-12-10 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0002_alter_recruitnotice_options_and_more'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitnotice',
            name='attachment',
        ),
        migrations.AddField(
            model_name='recruitnotice',
            name='attachment_urls',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recruitnotice',
            name='fee_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recruitnotice',
            name='region',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recruitnotice',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.school'),
        ),
        migrations.AlterField(
            model_name='recruitnotice',
            name='status',
            field=models.CharField(default='예정', max_length=20),
        ),
        migrations.AlterField(
            model_name='recruitnotice',
            name='submit_method',
            field=models.CharField(max_length=200),
        ),
    ]
