# Generated by Django 5.1.5 on 2025-12-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0003_remove_recruitnotice_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitnotice',
            name='neulbom_mng_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recruitnotice',
            name='neulbom_mode',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
