# Generated by Django 5.1.5 on 2025-12-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0004_recruitnotice_neulbom_mng_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitnotice',
            name='neulbom_mng_no',
        ),
        migrations.RemoveField(
            model_name='recruitnotice',
            name='neulbom_mode',
        ),
        migrations.RemoveField(
            model_name='recruitnotice',
            name='program',
        ),
        migrations.AddField(
            model_name='recruitnotice',
            name='programs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
