# Generated by Django 5.1.5 on 2025-12-10 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0005_remove_recruitnotice_neulbom_mng_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitnotice',
            name='fee_amount',
        ),
    ]
