# Generated by Django 5.1.5 on 2025-12-11 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0006_remove_recruitnotice_fee_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitnotice',
            name='fee_type',
        ),
    ]
