# Generated by Django 5.1.5 on 2025-12-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0007_remove_recruitnotice_fee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitnotice',
            name='is_our_school',
            field=models.BooleanField(default=False, verbose_name='우리 강사 출강 학교'),
        ),
    ]
