# Generated by Django 5.1.5 on 2025-12-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0009_alter_recruitnotice_is_our_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitnotice',
            name='is_our_school',
            field=models.BooleanField(default=False, null=True, verbose_name='우리 강사 출강 학교'),
        ),
    ]
