# Generated by Django 5.1.5 on 2026-01-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0010_alter_recruitnotice_is_our_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='프로그램명')),
                ('day', models.IntegerField(choices=[(1, '월'), (2, '화'), (3, '수'), (4, '목'), (5, '금'), (6, '토')], verbose_name='요일')),
                ('start_time', models.TimeField(verbose_name='시작 시간')),
                ('end_time', models.TimeField(verbose_name='종료 시간')),
                ('capacity', models.PositiveIntegerField(verbose_name='정원')),
            ],
        ),
    ]
