# Generated by Django 5.1.5 on 2026-01-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0011_recruitprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitprogram',
            name='color_class',
            field=models.CharField(default='timetable-blue', help_text='CSS 클래스명 (예: timetable-blue)', max_length=30, verbose_name='시간표 색상'),
        ),
    ]
