# Generated by Django 5.1.5 on 2026-06-12 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_kakao_name'),
        ('recruit', '0012_recruitprogram_color_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorRecruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='공고명')),
                ('description', models.TextField(blank=True, verbose_name='상세내용/소개')),
                ('recruit_start', models.DateTimeField(verbose_name='모집 시작일')),
                ('recruit_end', models.DateTimeField(verbose_name='모집 마감일')),
                ('capacity', models.PositiveIntegerField(default=0, help_text='0이면 제한 없음', verbose_name='모집 정원')),
                ('status', models.CharField(choices=[('open', '모집중'), ('closed', '마감'), ('hidden', '비공개')], default='hidden', max_length=20, verbose_name='상태')),
                ('image', models.ImageField(blank=True, null=True, upload_to='instructor_recruits/', verbose_name='대표 이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '지도사과정 모집 공고',
                'verbose_name_plural': '지도사과정 모집 공고',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstructorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=100, verbose_name='이름')),
                ('phone', models.CharField(max_length=30, verbose_name='연락처')),
                ('memo', models.TextField(blank=True, verbose_name='지원동기 및 남길말')),
                ('status', models.CharField(choices=[('pending', '신청완료'), ('approved', '승인'), ('rejected', '반려'), ('cancelled', '취소')], default='pending', max_length=20, verbose_name='상태')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_applications', to='accounts.profile', verbose_name='지원자(회원)')),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruit.instructorrecruit', verbose_name='공고')),
            ],
            options={
                'verbose_name': '지도사과정 지원 내역',
                'verbose_name_plural': '지도사과정 지원 내역',
                'ordering': ['-applied_at'],
            },
        ),
    ]
