# Generated by Django 5.1.5 on 2026-06-12 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0013_instructorrecruit_instructorapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorCourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='과정명')),
                ('default_description', models.TextField(blank=True, verbose_name='기본 상세내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '지도사과정 유형',
                'verbose_name_plural': '지도사과정 유형 목록',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='instructorrecruit',
            name='course_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruit.instructorcoursetype', verbose_name='과정 종류'),
        ),
    ]
