# Generated by Django 5.1.5 on 2026-06-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0014_instructorcoursetype_instructorrecruit_course_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorcoursetype',
            name='default_description',
        ),
        migrations.RemoveField(
            model_name='instructorrecruit',
            name='description',
        ),
        migrations.AddField(
            model_name='instructorcoursetype',
            name='cost_certificate',
            field=models.PositiveIntegerField(default=0, verbose_name='자격발급비'),
        ),
        migrations.AddField(
            model_name='instructorcoursetype',
            name='cost_education',
            field=models.PositiveIntegerField(default=0, verbose_name='교육비'),
        ),
        migrations.AddField(
            model_name='instructorcoursetype',
            name='cost_material',
            field=models.PositiveIntegerField(default=0, verbose_name='교재/교구비'),
        ),
        migrations.AddField(
            model_name='instructorcoursetype',
            name='course_intro',
            field=models.TextField(blank=True, verbose_name='과정 소개'),
        ),
        migrations.AddField(
            model_name='instructorcoursetype',
            name='curriculum',
            field=models.JSONField(blank=True, default=list, verbose_name='커리큘럼'),
        ),
        migrations.AddField(
            model_name='instructorcoursetype',
            name='educational_goal',
            field=models.TextField(blank=True, verbose_name='교육 목표'),
        ),
        migrations.AddField(
            model_name='instructorrecruit',
            name='cost_certificate',
            field=models.PositiveIntegerField(default=0, verbose_name='자격발급비'),
        ),
        migrations.AddField(
            model_name='instructorrecruit',
            name='cost_education',
            field=models.PositiveIntegerField(default=0, verbose_name='교육비'),
        ),
        migrations.AddField(
            model_name='instructorrecruit',
            name='cost_material',
            field=models.PositiveIntegerField(default=0, verbose_name='교재/교구비'),
        ),
        migrations.AddField(
            model_name='instructorrecruit',
            name='course_intro',
            field=models.TextField(blank=True, verbose_name='과정 소개'),
        ),
        migrations.AddField(
            model_name='instructorrecruit',
            name='curriculum',
            field=models.JSONField(blank=True, default=list, verbose_name='커리큘럼'),
        ),
        migrations.AddField(
            model_name='instructorrecruit',
            name='educational_goal',
            field=models.TextField(blank=True, verbose_name='교육 목표'),
        ),
    ]
