# Generated by Django 5.1.5 on 2026-06-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0015_remove_instructorcoursetype_default_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorcoursetype',
            name='cost_includes_all',
            field=models.BooleanField(default=False, verbose_name='비용 일체 포함 여부'),
        ),
        migrations.AddField(
            model_name='instructorrecruit',
            name='cost_includes_all',
            field=models.BooleanField(default=False, verbose_name='비용 일체 포함 여부'),
        ),
    ]
