# Generated by Django 5.1.5 on 2026-06-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0016_instructorcoursetype_cost_includes_all_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorcoursetype',
            name='certificate_agency',
            field=models.CharField(blank=True, max_length=100, verbose_name='발급기관'),
        ),
        migrations.AddField(
            model_name='instructorcoursetype',
            name='certificate_type',
            field=models.CharField(blank=True, choices=[('national', '국가자격'), ('authorized', '국가공인'), ('private', '민간자격'), ('none', '해당없음/수료증')], max_length=20, verbose_name='자격증 종류'),
        ),
        migrations.AddField(
            model_name='instructorrecruit',
            name='certificate_agency',
            field=models.CharField(blank=True, max_length=100, verbose_name='발급기관'),
        ),
        migrations.AddField(
            model_name='instructorrecruit',
            name='certificate_type',
            field=models.CharField(blank=True, choices=[('national', '국가자격'), ('authorized', '국가공인'), ('private', '민간자격'), ('none', '해당없음/수료증')], max_length=20, verbose_name='자격증 종류'),
        ),
    ]
