# Generated by Django 5.1.5 on 2026-06-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0017_instructorcoursetype_certificate_agency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructorcoursetype',
            options={'ordering': ['name'], 'verbose_name': '지도사과정 유형', 'verbose_name_plural': '지도사과정 유형'},
        ),
        migrations.AddField(
            model_name='instructorcoursetype',
            name='benefits',
            field=models.TextField(blank=True, verbose_name='제공혜택'),
        ),
        migrations.AddField(
            model_name='instructorcoursetype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='instructorrecruit',
            name='benefits',
            field=models.TextField(blank=True, verbose_name='제공혜택'),
        ),
    ]
