# Generated by Django 5.1.5 on 2026-06-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0018_alter_instructorcoursetype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorrecruit',
            name='class_days',
            field=models.CharField(blank=True, max_length=50, verbose_name='수업 요일'),
        ),
        migrations.AddField(
            model_name='instructorrecruit',
            name='class_time',
            field=models.CharField(blank=True, max_length=100, verbose_name='수업 시간'),
        ),
    ]
