# Generated by Django 5.1.5 on 2026-07-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0019_instructorrecruit_class_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorrecruit',
            name='class_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='수업 종료일'),
        ),
        migrations.AddField(
            model_name='instructorrecruit',
            name='class_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='수업 시작일'),
        ),
    ]
