# Generated by Django 4.2.29 on 2026-05-22 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0034_released_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fintech_use_num', models.CharField(max_length=100, unique=True, verbose_name='핀테크이용번호')),
                ('bank_code', models.CharField(max_length=10, verbose_name='은행코드')),
                ('bank_name', models.CharField(max_length=50, verbose_name='은행명')),
                ('account_num_masked', models.CharField(max_length=50, verbose_name='마스킹 계좌번호')),
                ('account_holder', models.CharField(blank=True, max_length=50, verbose_name='예금주')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용중')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '등록 계좌',
                'verbose_name_plural': '등록 계좌',
            },
        ),
        migrations.CreateModel(
            name='OpenBankingToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_seq_no', models.CharField(blank=True, max_length=50, verbose_name='오픈뱅킹 사용자일련번호')),
                ('access_token', models.TextField(verbose_name='액세스 토큰')),
                ('refresh_token', models.TextField(blank=True, verbose_name='리프레시 토큰')),
                ('expires_at', models.DateTimeField(verbose_name='만료일시')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='openbanking_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '오픈뱅킹 토큰',
                'verbose_name_plural': '오픈뱅킹 토큰',
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_date', models.DateField(verbose_name='거래일')),
                ('tran_time', models.CharField(max_length=6, verbose_name='거래시각')),
                ('tran_type', models.CharField(max_length=10, verbose_name='거래구분')),
                ('tran_amt', models.BigIntegerField(verbose_name='거래금액')),
                ('balance_amt', models.BigIntegerField(default=0, verbose_name='잔액')),
                ('print_content', models.CharField(blank=True, max_length=200, verbose_name='거래내용(통장표시)')),
                ('branch_name', models.CharField(blank=True, max_length=100, verbose_name='점명')),
                ('tran_unique_no', models.CharField(max_length=100, unique=True, verbose_name='거래고유번호')),
                ('is_auto_matched', models.BooleanField(default=False, verbose_name='자동매칭')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='openbanking.registeredaccount')),
                ('matched_release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='materials.materialrelease', verbose_name='매칭된 출고')),
            ],
            options={
                'verbose_name': '은행 거래내역',
                'verbose_name_plural': '은행 거래내역',
                'ordering': ['-tran_date', '-tran_time'],
            },
        ),
    ]
