# Generated by Django 5.1.5 on 2025-11-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255, verbose_name='주제(내부용)')),
                ('main_title', models.CharField(max_length=255, verbose_name='선택된 제목')),
                ('alt_titles', models.JSONField(blank=True, default=list, verbose_name='대체 제목들')),
                ('category', models.CharField(choices=[('ai_aice', 'AI / AICE'), ('robot_coding', '로봇 코딩'), ('creative_math', '창의수학'), ('science', '과학탐구'), ('teacher_training', '강사 교육')], default='ai_aice', max_length=50, verbose_name='카테고리')),
                ('raw_response', models.JSONField(blank=True, null=True, verbose_name='GPT 원본 응답(JSON)')),
                ('content', models.TextField(verbose_name='본문 내용')),
                ('keywords', models.JSONField(blank=True, default=list, verbose_name='키워드 리스트')),
                ('cta', models.CharField(blank=True, max_length=500, verbose_name='CTA 문구')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='blog_thumbnails/', verbose_name='썸네일 이미지')),
                ('platform', models.CharField(choices=[('naver', '네이버만'), ('tistory', '티스토리만'), ('both', '두 곳 모두')], default='both', max_length=20, verbose_name='발행 플랫폼')),
                ('status', models.CharField(choices=[('draft', '작성중'), ('ready', '발행 준비'), ('scheduled', '예약'), ('published', '발행 완료'), ('failed', '실패')], default='draft', max_length=20, verbose_name='상태')),
                ('publish_at', models.DateTimeField(blank=True, null=True, verbose_name='예약 발행 시간')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='실제 발행 시간')),
                ('naver_post_id', models.CharField(blank=True, max_length=100, verbose_name='네이버 포스트 ID')),
                ('tistory_post_id', models.CharField(blank=True, max_length=100, verbose_name='티스토리 포스트 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
