# Generated by Django 5.1.5 on 2026-08-28 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0004_student_is_priority'),
        ('teachers', '0018_consolidate_afterschool_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='조 이름')),
                ('position_row', models.PositiveIntegerField(verbose_name='배치 행')),
                ('position_col', models.PositiveIntegerField(verbose_name='배치 열')),
                ('seat_rows', models.PositiveIntegerField(default=2, verbose_name='조 내 좌석 행 수')),
                ('seat_cols', models.PositiveIntegerField(default=2, verbose_name='조 내 좌석 열 수')),
            ],
            options={
                'ordering': ['position_row', 'position_col'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField(verbose_name='조 내 좌석 번호')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='seating.seatgroup')),
            ],
            options={
                'ordering': ['seat_number'],
            },
        ),
        migrations.CreateModel(
            name='SeatLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_col_counts', models.CharField(default='2,2', max_length=200, verbose_name='행별 조 열 수')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seat_layout', to='teachers.teachinginstitution')),
            ],
        ),
        migrations.AddField(
            model_name='seatgroup',
            name='layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='seating.seatlayout'),
        ),
        migrations.CreateModel(
            name='SeatAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_assignments', to='students.programdivision')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='seating.seat')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seat_assignment', to='students.student')),
            ],
            options={
                'unique_together': {('seat', 'division')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='seatgroup',
            unique_together={('layout', 'position_row', 'position_col')},
        ),
    ]
