# Generated by Django 5.1.5 on 2025-10-30 14:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RobotLevelUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='화정남초', max_length=100, verbose_name='학교명')),
                ('year_month', models.CharField(max_length=20, verbose_name='년월')),
                ('kit_name', models.CharField(max_length=50, verbose_name='교구명')),
                ('section', models.CharField(blank=True, max_length=20, verbose_name='부')),
                ('grade', models.PositiveIntegerField(blank=True, null=True, verbose_name='학년')),
                ('class_no', models.PositiveIntegerField(blank=True, null=True, verbose_name='반')),
                ('student_no', models.PositiveIntegerField(blank=True, null=True, verbose_name='번호')),
                ('student_name', models.CharField(max_length=50, verbose_name='학생명')),
                ('guide', models.BooleanField(default=False, verbose_name='안내')),
                ('release', models.BooleanField(default=False, verbose_name='출고')),
                ('delivery', models.BooleanField(default=False, verbose_name='전달')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='가격')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='비고')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '로봇 단계업',
                'verbose_name_plural': '로봇 단계업 관리',
                'ordering': ['-created_at'],
            },
        ),
    ]
