# Generated by Django 5.1.5 on 2025-10-30 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0031_materialrelease_created_by'),
        ('robot_LvUP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robotlevelup',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='robotlevelup',
            name='guide',
        ),
        migrations.RemoveField(
            model_name='robotlevelup',
            name='kit_name',
        ),
        migrations.RemoveField(
            model_name='robotlevelup',
            name='release',
        ),
        migrations.AddField(
            model_name='robotlevelup',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='전달일'),
        ),
        migrations.AddField(
            model_name='robotlevelup',
            name='delivery_done',
            field=models.BooleanField(default=False, verbose_name='전달완료'),
        ),
        migrations.AddField(
            model_name='robotlevelup',
            name='guide_date',
            field=models.DateField(blank=True, null=True, verbose_name='안내일'),
        ),
        migrations.AddField(
            model_name='robotlevelup',
            name='guide_done',
            field=models.BooleanField(default=False, verbose_name='안내완료'),
        ),
        migrations.AddField(
            model_name='robotlevelup',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='materials.material', verbose_name='교구명'),
        ),
        migrations.AddField(
            model_name='robotlevelup',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='출고일'),
        ),
        migrations.AddField(
            model_name='robotlevelup',
            name='release_done',
            field=models.BooleanField(default=False, verbose_name='출고완료'),
        ),
        migrations.AlterField(
            model_name='robotlevelup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='robotlevelup',
            name='year_month',
            field=models.CharField(help_text='예: 2025-11', max_length=7, verbose_name='년월'),
        ),
    ]
