# Generated by Django 5.1.5 on 2025-11-06 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_LvUP', '0002_remove_robotlevelup_delivery_and_more'),
        ('teachers', '0007_career_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotlevelup',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levelups', to='teachers.teachinginstitution', verbose_name='출강장소'),
        ),
    ]
