# Generated by Django 5.1.5 on 2025-11-06 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot_LvUP', '0003_robotlevelup_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robotlevelup',
            name='school_name',
        ),
    ]
