# Generated by Django 4.2.29 on 2026-05-20 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_programdivision_institution_delete_institution'),
        ('robot_LvUP', '0005_robotlevelup_shipped_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotlevelup',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='levelups', to='students.student', verbose_name='학생'),
        ),
    ]
