# Generated by Django 5.1.5 on 2025-04-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('1부', '1부'), ('2부', '2부'), ('3부', '3부')], default='1부', max_length=10),
        ),
    ]
