# Generated by Django 5.1.5 on 2025-04-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_student_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('출석', '출석'), ('지각', '지각'), ('결석', '결석')], default='출석', max_length=10),
        ),
    ]
