# Generated by Django 5.1.5 on 2025-04-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_school_student_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='address',
        ),
        migrations.AddField(
            model_name='school',
            name='program_name',
            field=models.CharField(default='기본프로그램', help_text='운영 프로그램명 (예: 로봇과학반)', max_length=100),
        ),
    ]
