# Generated by Django 5.1.5 on 2025-09-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('url', models.URLField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
