# Generated by Django 5.1.5 on 2025-10-15 01:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamiclink',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='dynamiclink',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dynamiclink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dynamiclink',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dynamiclink',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
